# coding: utf-8

# flake8: noqa
"""
    Open Message Format

    This specification defines an API contract between client and server for building conversational agents, and defines a standard schema for the \"messages\" object, which contains user and assistant interactions. The \"messages\" object schema serves a dual purpose, to capture user and assistant conversation from client to your back-end, and from your back-end server to an upstream LLM 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.content_item import ContentItem
from openapi_client.models.message import Message
from openapi_client.models.message_content import MessageContent
from openapi_client.models.metadata import Metadata
from openapi_client.models.response_message import ResponseMessage
